name: CI

on: push

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"

      - name: Build with Maven
        run: mvn clean package -DskipTests
        
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: moviecards-java
          path: "${{ github.workspace }}/target/*.jar"

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: pruebas
        run: echo "pruebas"
  
  qa:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: calidad
        run: echo "calidad"

  deploy:
    needs: qa
    runs-on: ubuntu-latest
    steps:
      - name: despliegue
        run: echo "despliegue"
